### ISSUE TITLE
spike: SDK refactoring

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-sdk#112]
**🧩 Pragma SDK 2.0 Tasks**
- [x] Remove offchain mixin #111 
- [x] Rewrite Nonce Mixin such that it correctly takes into account pending blocks and avoid failed txs
- [x] Refactor logging logic
- [x] Remove unused code
- [x] Create more type aliases for clarity
- [x] Separate API from on-chain logic #111 
- [x] Refactor PublisherInterface to enable pair hoping
- [x] Add `SummaryStats` Mixin
- [x] Checkpoint Scheduler docker image + example deployment
- [x] Refactor Fetchers tests
- [x] Add more documentation #114 
- [x] Fix Linting in CI #116 
- [x] Change structure of the repo #123 
- [x] Switch to starknet-devnet-rs #122 
- [x] Switch from `TypedDict` to `dataclass`
